### ISSUE TITLE
BufferOverflowException

### ISSUE THREAD

**Issue by sanjaypanara** [shogo4405/HaishinKit.kt#206]
### Describe the bug

     com.magicpolygon.storycircles.debug  W  java.nio.BufferOverflowException
                                                                                                    	at java.nio.Buffer.nextPutIndex(Buffer.java:542)
                                                                                                    	at java.nio.HeapByteBuffer.putDouble(HeapByteBuffer.java:539)
                                                                                                    	at com.haishinkit.amf.Amf0Serializer.putDouble(Amf0Serializer.kt:17)
                                                                                                    	at com.haishinkit.amf.Amf0Serializer.putObject(Amf0Serializer.kt:89)
                                                                                                    	at com.haishinkit.amf.Amf0Serializer.putMap(Amf0Serializer.kt:39)
                                                                                                    	at com.haishinkit.rtmp.message.RtmpCommandMessage.encode(RtmpCommandMessage.kt:28)
                                                                                                    	at com.haishinkit.rtmp.RtmpChunk.encode(RtmpChunk.kt:15)
                                                                                                    	at com.haishinkit.rtmp.RtmpConnection.doOutput$haishinkit_release(RtmpConnection.kt:263)
                                                                                                    	at com.haishinkit.rtmp.RtmpSocket.onInput(RtmpSocket.kt:121)
                                                                                                    	at com.haishinkit.net.NetSocketImpl.doInput(NetSocketImpl.kt:107)
                                                                                                    	at com.haishinkit.net.NetSocketImpl.doConnection(NetSocketImpl.kt:167)
                                                                                                    	at com.haishinkit.net.NetSocketImpl.access$doConnection(NetSocketImpl.kt:21)
                                                                                                    	at com.haishinkit.net.NetSocketImpl$connect$1.invokeSuspend(NetSocketImpl.kt:60)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### To Reproduce

When user multipal time start and stop live telecast.

### Expected behavior

When user multipal time start and stop live telecast.

### Version

0.11.0

**Comment by shogo4405** [comment]
What is telecast? Is it about the service name?

**Comment by sanjaypanara** [comment]
> What is telecast? Is it about the service name?


When a user repeatedly starts and stops live broadcasting, this problem occurs.
