### ISSUE TITLE
HkSurfaceViewを使うと配信終了処理でクラッシュしてしまいます。

### ISSUE THREAD

**Issue by n-kazukichi** [shogo4405/HaishinKit.kt#44]
**Describe the bug**
HkSurfaceView利用時、RtmpConnection.close()を呼んだタイミングで
次の例外が繰り返し発生しクラッシュしてしまいました。
```
2022-03-11 09:03:56.606 6720-6720/com.haishinkit.studio E/AndroidRuntime:     at com.haishinkit.view.HkSurfaceView.stopRunning(HkSurfaceView.kt:86)
        at com.haishinkit.media.Camera2Source.stopRunning(Camera2Source.kt:176)
        at com.haishinkit.view.HkSurfaceView.stopRunning(HkSurfaceView.kt:86)
        at com.haishinkit.media.Camera2Source.stopRunning(Camera2Source.kt:176)
        at com.haishinkit.view.HkSurfaceView.stopRunning(HkSurfaceView.kt:86)
        ...以下 StackOverflowが発生するまで繰り返し
```

**To Reproduce**
1. サンプルのHaishinStudioを実機で起動します
2. Publichボタンをクリックします。
3. Stopボタンをクリックします。

**Smartphone**
 - Device: Lenovo M10 Tab
 - OS: Android10.0
--
 - Device: LG Nexus 5X
 - OS: Android8.1

**Comment by shogo4405** [comment]
報告ありがとうございます。修正しました。
クラッシュはよくないので0.7.1として明日くらいにリリースしようと思います。

**Comment by n-kazukichi** [comment]
迅速なご対応ありがとうございます。
前述の実機において、クラッシュしなくなりました。
